"_id": "5553a998e4b02cf7151190ba","st": "x+51900+003600","ts": "1984-03-05T14:00:00.000Z","position.type": "Point","position.coordinates": [3.6, 51.9],"elevation": 9999,"callLetters": "PLAT","qualityControlProcess": "V020","dataSource": "4","type": "FM-13","airTemperature.value": 4.4,"airTemperature.quality": "1","dewPoint.value": 3.5,"dewPoint.quality": "1","pressure.value": 1030.8,"pressure.quality": "1","wind.direction.angle": 200,"wind.direction.quality": "1","wind.type": "N","wind.speed.rate": 1,"wind.speedquality": "1","visibility.distance.value": 999999,"visibility.distance.quality": "9","variability.value": "N","variability.quality": "9","skyCondition.ceilingHeight.value": 99999,"skyCondition.ceilingHeight.quality": "9","skyCondition.ceilingHeight.determination": "9","skyCondition.cavok": "N","sections": ["AG1", "MD1", "OA1", "SA1", "UA1"],"precipitationEstimatedObservation.discrepancy": "2",
"precipitationEstimatedObservation.estimatedWaterDepth": 999,
"atmosphericPressureChange.tendency.code": "2",
"atmosphericPressureChange.tendency.quality": "1",
"atmosphericPressureChange.quantity3Hours.value": 0.9,
"atmosphericPressureChange.quantity3Hours.quality": "1",
"atmosphericPressureChange.quantity24Hours.value": 99.9,
"atmosphericPressureChange.quantity24Hours.quality": "9",
"seaSurfaceTemperature.value": 4.5,
"seaSurfaceTemperature.quality": "9",
"waveMeasurement": {
"waveMeasurement.waves.period": 4,
"waveMeasurement.waves.height": 0.5,
"waveMeasurement.waves.quality": "9",
"waveMeasurement.seaState.code": "99",
"waveMeasurement.seaState.quality": "9",
